# -*- coding: utf-8 -*-
"""201844082_박훈희_멜론차트.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13y1H_i5PI4u6gmwuBHD0rs7NhMxqmKn4
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
 
if __name__ == "__main__":
    RANK = 100
    result_df = pd.DataFrame()
 
    header = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko'}
    req = requests.get('https://www.melon.com/chart/index.htm', headers = header)
    html = req.text
    parse = BeautifulSoup(html, 'html.parser')
 
    titles = parse.find_all("div", {"class": "ellipsis rank01"})
    songs = parse.find_all("div", {"class": "ellipsis rank02"})
 
    title = []
    song = []
    rank = []
 
    for t in titles:
        title.append(t.find('a').text)
 
    for s in songs:
        song.append(s.find('span', {"class": "checkEllipsis"}).text)
 
    for i in range(RANK):
        rank.append(i+1);
        print('%3d위: %s - %s'%(i+1, title[i], song[i]))

    df = pd.DataFrame({'순위':rank,'곡명':title,'가수명':song})
    result_df = pd.concat([result_df, df], ignore_index=True)
    result_df.to_csv('melon.csv')